#!/bin/sh
# Begin $rc_base/init.d/nas

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 19:29:19 +0000 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
        start)
                boot_mesg "Starting the Network Audio System Server..."
		loadproc /usr/X11R6/bin/nasd -aa -b
#                pidof nasd
#                if test $? = "0"
#                then
#                        print_status warning running
#                else
#                        /usr/X11R6/bin/nasd -aa &
#                        pidof /usr/X11R6/bin/nasd
#                        if test $? = "0" ; then
#                                print_status success
#                        else
#                                print_status failure
#                        fi
#                fi
		;;

        stop)
                boot_mesg "Stopping the Network Audio System Server..."
                killproc /usr/X11R6/bin/nasd
                ;;

        reload)
                boot_mesg "Reloading the Network Audio System Server..."
                reloadproc /usr/X11R6/bin/nasd
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc /usr/X11R6/bin/nasd
                ;;

        *)
                echo "Usage: $0 {start|stop|reload|restart|status}"
                exit 1
                ;;
esac

# End $rc_base/init.d/nasd
