#!/bin/sh
# Begin $rc_base/init.d/ntp

#$LastChangedBy: dnicholson $
#$Date: 2008-03-12 21:45:44 +0000 (Wed, 12 Mar 2008) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting ntpd..."
		ntpd -gqx
		loadproc /usr/sbin/ntpd
		;;

	stop)
		boot_mesg "Stopping ntpd..."
		killproc /usr/sbin/ntpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/ntpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/ntp
