#!/bin/sh
# Begin $rc_base/init.d/proftpd

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 19:29:19 +0000 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting FTP Server..."
		loadproc /usr/sbin/proftpd
		;;

	stop)
		boot_mesg "Stopping FTP Server..."
		killproc /usr/sbin/proftpd
		;;

	reload)
		boot_mesg "Reloading FTP Server..."
		reloadproc /usr/sbin/proftpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/proftpd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/proftpd
