#!/bin/sh
# Begin $rc_base/init.d/sendmail

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 19:29:19 +0000 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting sendmail..."
		loadproc /usr/sbin/sendmail -bs -bd -q5m start
		;;

	stop)
		boot_mesg "Stopping Sendmail..."
		killproc /usr/sbin/sendmail
		;;

	status)
		statusproc /usr/sbin/sendmail
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
esac

# End $rc_base/init.d/sendmail
