#!/usr/bin/env perl
use strict;
use warnings;

my $shell_command = 'ntpdate pool.ntp.org';

system("date >> /tmp/ntp.date");
system $shell_command;
system("date >> /tmp/ntp.date");
system("hwclock --systohc --utc");

