#!/usr/bin/env perl
use DBI;
use warnings;
use strict;
# use Date::Format;

print "\n----------------------------------------------------------------";
my $package_id = $ARGV[0];
my $CSV_DIR = "/home/troy/rcs/stowball/data/shilohSchema/2010_spring/csv";
my $packages_csv_file = $CSV_DIR . '/packages.csv';

my $dbh = DBI->connect ("DBI:CSV:f_dir=$CSV_DIR") or
    die "Cannot connect: $DBI::errstr";
$dbh->{csv_tables}{packages} = {
    file => $packages_csv_file,
    col_names => [
	"id",
	"short_name",
	"name",
	"latest_version",
	"date_released",
	"date_checked"
	]
};
my $result = $dbh->selectall_arrayref("SELECT id, short_name, latest_version, date_checked FROM packages ORDER BY date_checked DESC");
foreach my $row (@$result) {
    my ( $id, $short_name, $version, $date_checked ) = @$row;
    print "\n$id: $short_name [$version]\t$date_checked";
}


$dbh->do("UPDATE packages SET date_checked = '2010-04-09' WHERE id = 9");

$dbh->disconnect;

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) =
    localtime(time);
my $iso_date = sprintf("%4d-%02d-%02d",($year + 1900), ++$mon, $mday);
print "\n$iso_date\n";
exit;
