#!/bin/bash
set -o errexit
# TDW <troydwill@gmail.com> 2009-12-16
# Could not load host key: /etc/ssh/ssh_host_rsa_key
# Could not load host key: /etc/ssh/ssh_host_dsa_key
# Disabling protocol version 2. Could not load host key
# sshd: no hostkeys available -- exiting.
ssh-keygen -type rsa -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -type dsa -f /etc/ssh/ssh_host_dsa_key
