#!/bin/sh
# Begin $rc_base/init.d/gdm

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: dnicholson $
#$Date: 2008-03-12 21:45:44 +0000 (Wed, 12 Mar 2008) $

. /etc/sysconfig/rc
. $rc_functions

pidfile=/var/run/gdm.pid

export PATH=$PATH:/opt/gnome-2.18.3/bin:/opt/gnome-2.18.3/sbin

case "$1" in
	start)
		boot_mesg "Starting GDM..."
		loadproc gdm
		;;

	stop)
		boot_mesg "Stopping GDM..."
		if [ -f $pidfile ]; then
			loadproc gdm-stop
		fi
		;;

	reload)
		boot_mesg "Reloading GDM..."
		loadproc gdm-safe-restart
		;;

	restart)
		boot_mesg "Restarting GDM..."
		loadproc gdm-restart
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart}"
		exit 1
		;;
esac

# End $rc_base/init.d/gdm
