#!/bin/sh
# Begin $rc_base/init.d/bind

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2006-06-09 03:01:47 +0000 (Fri, 09 Jun 2006) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting named..."
		loadproc /usr/sbin/named -u named -t /srv/named -c \
			/etc/named.conf
		;;

	stop)
		boot_mesg "Stopping named..."
		killproc /usr/sbin/named
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	reload)
		boot_mesg "Reloading named..."
		/usr/sbin/rndc -c /etc/rndc.conf reload
		;;

	status)
		statusproc /usr/sbin/named
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/bind
