#!/bin/sh
# Begin $rc_base/init.d/dhcp

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: dnicholson $
#$Date: 2007-12-21 18:21:44 +0000 (Fri, 21 Dec 2007) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting DHCP Server..."
		loadproc /usr/sbin/dhcpd -q eth1
		;;

	stop)
		boot_mesg "Stopping DHCP Server..."
		killproc /usr/sbin/dhcpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/dhcpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/dhcp
