#!/bin/sh
# Begin $rc_base/init.d/kerberos

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 19:29:19 +0000 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
        start)  
                boot_mesg "Starting Kerberos Authentication..."
                loadproc krb5kdc
                boot_mesg "Starting Kerberos Admin Daemon..."
                loadproc kadmind
                ;;

        stop)
                boot_mesg "Stopping Kerberos Authentication..."
                killproc krb5kdc
                boot_mesg "Stopping Kerberos Admin Daemon..."
                killproc kadmind
                ;;

        reload)
                boot_mesg "Reloading Kerberos Authentication..."
                reloadproc krb5kdc
                boot_mesg "Reloading Kerberos Admin Daemon..."
                reloadproc kadmind
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc
                ;;

        *)
                echo "Usage: $0 {start|stop|reload|restart|status}"
                exit 1
                ;;
esac
# End $rc_base/init.d/kerberos
