#!/bin/bash
set -o errexit
PACKAGE="mplayer"
VERSION="091119"
PACKAGER="TDW <troydwill@gmail.com>"
DATE="2009-12-16"
PREFIX="/usr"
TARGET="/"
STOW_DIR="/stow"
SUDO="sudo"

PACKAGE_DIR=${PACKAGE}-${VERSION}

do_configure () {
    ./configure --prefix=/usr \
        --confdir=/etc/mplayer \
        --enable-largefiles \
        --enable-dynamic-plugins \
	--codecsdir=/usr/lib/mplayer/codecs/ \
	--enable-debug=3 \
	--disable-fontconfig \
	2>&1 | tee log.stow.configure
}

do_build () {
    make 2>&1 | tee log.stow.make
}

do_install () {
    ${SUDO} make DESTDIR=${STOW_DIR}/${PACKAGE_DIR} install 2>&1 | tee log.stow.install
}

do_stow () {
    ${SUDO} stow -v --target=${TARGET} --dir=${STOW_DIR} ${PACKAGE_DIR} 2>&1 | tee log.stow.stow
}

do_poststow () {
    echo "run makeinfo"
}

do_package () {
    cd /tmp
    ${SUDO} tar -jcf ${PACKAGE_DIR}.stow.tar.bz2 ${STOW_DIR}${PACKAGE_DIR}
}

do_configure
do_build
do_install
do_stow
do_poststow
# do_package
