#!/usr/bin/env perl
use strict;
use warnings;
use DBI;
my $delay = $ARGV[0] or 10;

my $DATABASE = '/var/lib/stowball/2010_spring.db';
my $dbh =
  DBI->connect( "dbi:SQLite:$DATABASE", "", "",
    { RaiseError => 1, AutoCommit => 1 } );

&order_software_by_date_checked;

# &packages_with_urls;

sub order_software_by_date_checked {
    open( HTML, '>software.html' );
    my $all = $dbh->selectall_arrayref(
        "SELECT * FROM packages ORDER BY date_checked DESC");
    print HTML "<table border=1>\n";
    foreach my $row (@$all) {
        my ( $id, $short_name, $name, $latest_version, $date_released,
            $date_checked )
          = @$row;
        print "$date_checked $id: $short_name\n";

        my $website =
          $dbh->selectall_arrayref("SELECT * FROM webpages WHERE id = $id");
        foreach my $row (@$website) {
            my ( $id, $homepage_url, $wikipedia_url, $lfs_url, $date_checked ) =
              @$row;
            print "\t$id\t$homepage_url\n";
            system("/usr/local/bin/arora $homepage_url &");
            sleep $delay;

        }
    }
    print HTML "</table>\n";
}

sub packages_with_urls {
    open( HTML, '>urls.html' );
    my $all = $dbh->selectall_arrayref("SELECT * FROM packages ORDER BY id");
    print HTML "<table border=1>\n";

    # Loop through all packages
    foreach my $row (@$all) {
        my ( $id, $short_name, $name, $latest_version, $date_checked ) = @$row;
        my $tarball = $dbh->selectall_arrayref(
            "SELECT * FROM latest_tarball WHERE id = \'$id\'");
        foreach my $row (@$tarball) {
            my ( $id, $latest_tarball, $url, $date_checked ) = @$row;
            print "DEBUG => $id, $latest_tarball, $date_checked, $url <==\n";
            print HTML
"<tr><td>$id</td><td>$short_name</td><td>$url</td><td>$date_checked</td></tr>\n";
        }
    }
    print HTML "</table>\n";
    close HTML;
}
