#!/usr/bin/perl
use warnings;
use strict;

&write_conf_file;

sub write_conf_file {
    open (CONF, ">/etc/ntp.conf");
    print CONF<<'EOF'
# Africa
server tock.nml.csir.co.za

# Asia
server 0.asia.pool.ntp.org

# Australia
server 0.oceania.pool.ntp.org

# Europe
server 0.europe.pool.ntp.org

# North America
server 0.north-america.pool.ntp.org

# South America
server 2.south-america.pool.ntp.org

driftfile /var/cache/ntp.drift
pidfile   /var/run/ntpd.pid
EOF

}
