#!/usr/bin/env perl
use strict;
use warnings;

my $shell_command = 'ntpd --quit';

system("date > /tmp/ntp.date");
system $shell_command;
system("date >> /tmp/ntp.date");
system("hwclock --systohc");

