#!/bin/bash
set -o errexit
# 2009-12-17 <troydwill@gmail.com>
#  See http://www.linuxfromscratch.org/blfs/view/svn/basicnet/dhcpcd.html
# On an Asus EEE 900A the ethernet interface is eth1
# Your interface may be eth0
install -v -d /etc/sysconfig/network-devices/ifconfig.eth1
cat > /etc/sysconfig/network-devices/ifconfig.eth1/dhcpcd <<EOF
ONBOOT="yes"
SERVICE="dhcpcd"
DHCP_START=""
DHCP_STOP="-k"

# Set PRINTIP="yes" to have the script print
# the DHCP assigned IP address
PRINTIP="yes"

# Set PRINTALL="yes" to print the DHCP assigned values for
# IP, SM, DG, and 1st NS. This requires PRINTIP="yes".
PRINTALL="yes"
EOF
