#!/usr/bin/env perl
use warnings;
use strict;

my $SUDO_COMMAND = 'sudo';

# http://www.linuxfromscratch.org/blfs/view/svn/multimedia/alsa-utils.html
# 2009-11-22 TDW <troydwill@gmail.com>

# All sound devices are not accessible for any user except root and members of the audio group. Add any users that might use the sound devices to that group:

my $user = &input_user;
&add_permission( $user );

sub input_user {
    my $login = $ENV{'LOGNAME'};
    print %ENV;
    return $login;
}

sub add_permission {
    my $login = &input_user;
    my $shell_command = "$SUDO_COMMAND usermod --append --groups audio $login";
    print "Will execute this command: ==> $shell_command <==";
    system( $shell_command );
}
