#!/bin/sh
# Begin /etc/init.d/postfix

### BEGIN INIT INFO
# Provides:            postfix
# Required-Start:      $syslog $local_fs $network
# Should-Start:        $remote_fs
# Required-Stop:
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Postfix MTA
# Description:         Controls the Postfix Mail Transfer Agent
# X-LFS-Default-Start: S35
# X-LFS-Default-Stop:  K25
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="Postfix MTA"
BIN_FILE="/usr/lib/postfix/master"
CTRL_FILE="/usr/sbin/postfix"
CONFIG_FILE="/etc/postfix/main.cf"
PIDFILE="/var/spool/postfix/pid/master.pid"
# Make certain that the binary exists, and that the config file exists
chk_stat

case "$1" in

    start)
        start_daemon -p "${PIDFILE}" "${CTRL_FILE}" start 2> /dev/null
        evaluate_retval start
    ;;

    stop)
        start_daemon "${CTRL_FILE}" stop 2> /dev/null
        evaluate_retval stop
    ;;

    reload)
        start_daemon "${CTRL_FILE}" reload 2> /dev/null
        evaluate_retval reload
    ;;

    restart)
        # Restart service (if running) or start service
        start_daemon "${CTRL_FILE}" stop 2> /dev/null
        sleep 1
        start_daemon "${CTRL_FILE}" start 2> /dev/null
        evaluate_retval restart
    ;;

    status)
        statusproc "${BIN_FILE}" "Postfix MTA master process"
        #evaluate_retval status
    ;;

    *)
        echo "    Usage:  ${0}{start|stop|reload|restart|status}"
    ;;

esac

# End /etc/init.d/gpm

