#!/bin/sh
# Begin /etc/init.d/samba

### BEGIN INIT INFO
# Provides:            samba
# Required-Start:      $network
# Should-Start:        
# Required-Stop:       $network
# Should-Stop:         $remote_fs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Provides SMB (Windows) networking.
# Description:         Starts Samba smbd and nmbd processess which provide
#                      connectivity to SMB (Windows) networks.
# X-LFS-Default-Start: S45
# X-LFS-Default-Stop:  K48
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        MESSAGE="nmbd..."
        start_daemon /usr/sbin/nmbd -D
        evaluate_retval start

        MESSAGE="smbd..."
        start_daemon /usr/sbin/smbd -D
        evaluate_retval start
    ;;

    stop)
        MESSAGE="smbd..."
        killproc /usr/sbin/smbd
        evaluate_retval stop

        MESSAGE="nmbd..."
        killproc /usr/sbin/nmbd
        evaluate_retval stop
    ;;

	reload)
        MESSAGE="smbd..."
        killproc -HUP /usr/sbin/smbd
        evaluate_retval reload

        MESSAGE="nmbd..."
        killproc -HUP /usr/sbin/nmbd
        evlauate_retval reload
    ;;

    restart)
        $0 stop
        sleep 1
        $0 start
    ;;

    status)
        statusproc /usr/sbin/nmbd
        statusproc /usr/sbin/smbd
    ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
    ;;

esac

# End $rc_base/init.d/samba
