#!/bin/sh
# Begin $network-devices/services/ipx

# Based upon lfs-bootscripts-1.12 $network_devices/if{down,up}
# Rewritten by Nathan Coulson <nathan@linuxfromscratch.org>
# Adapted for ipx by DJ Lucas <dj@lucasit.com>

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 19:29:19 +0000 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc || exit
. $rc_functions || exit
. $IFCONFIG

case $2 in
        up)
                boot_mesg "Starting IPX on the $1 interface..."
                /bin/ipx_interface add $1 $FRAME &&
                /bin/ipx_configure --auto_interface=on --auto_primary=on
                evaluate_retval
        ;;

        down)
                boot_mesg "Stopping IPX on the $1 interface..."
                /bin/ipx_configure --auto_interface=off --auto_primary=off &&
                /bin/ipx_interface del $1 $FRAME
                evaluate_retval
        ;;

        *)
                echo echo "Usage: $0 [interface] {up|down}"
                exit 1
        ;;

esac

# End $network-devices/services/ipx
