#!/bin/bash
set -o errexit
# troydwill@gmail.com: Try to deuglify this; followed Beyond Linux From Scratch instructions
do_patch () {
    cd ..
    wget --no-clobber http://www.linuxfromscratch.org/patches/blfs/6.3/nss-3.11.7-with-nspr-4.6.7-fedora_fixes-1.patch
    cd -
    patch -Np1 -i ../nss-3.11.7-with-nspr-4.6.7-fedora_fixes-1.patch
}
# do_patch
do_set_environment () {
    export WORKINGDIR=$PWD
    export BUILD_OPT=1
    cd mozilla
    export NSS_LINUXDIR=$(basename `ls -d $WORKINGDIR/mozilla/dist/Linux*`)
    cd ..
}

do_build () {
    cd mozilla/security/nss &&
    make nss_build_all &&
    cd ../../..
    pwd
}

#   Now, as the root user:
do_install () {
    cd mozilla
    sudo install -v -m755 nsprpub/$NSS_LINUXDIR/config/nspr-config \
        security/nss/cmd/config/nss-config \
    	/usr/bin
    sudo install -v -m755 -d /usr/lib/pkgconfig
    sudo install -v -m644 nsprpub/lib/pkgconfig/nspr.pc \
        security/nss/lib/pkgconfig/nss.pc \
	/usr/lib/pkgconfig
    cd dist
    
    sudo install -v -m755 $NSS_LINUXDIR/lib/*.so /usr/lib
    sudo install -v -m644 $NSS_LINUXDIR/lib/{*.chk,libcrmf.a} /usr/lib
    
    sudo install -v -m755 -d /usr/include/{nss,nspr}
    sudo install -v -m644 {public,private}/nss/* /usr/include/nss
    sudo cp -v -RL $NSS_LINUXDIR/include/* /usr/include/nspr
    sudo chmod -v 644 /usr/include/nspr/prvrsion.h
    find /usr -type f -cmin -1 | nl
    exit    
}

echo "------------------------"
date
echo "------------------------"
do_set_environment
echo $NSS_LINUXDIR
do_install

exit
exit
exit

Command Explanations

   bash: Shells are started as many environment variables are created
   during the installation process. Exiting the shells serves the purpose
   of restoring the environment and returning back to the original
   directory when the installation is complete.

   export WORKINGDIR=$PWD: This variable is set because many of the
   commands are dependent on knowing the full path of certain directories.
   WORKINGDIR establishes a known path so that all others can be
   determined relative to this.

   export BUILD_OPT=1: This variable is set so that the build is performed
   with no debugging symbols built into the binaries and that the default
   compiler optimizations are used.

   export NSS_LINUXDIR=...: This variable is set so that the exact name of
   the architecture specific directories where the binaries are stored in
   the source tree can be determined.

   make nss_build_all: This command builds the NSPR and NSS libraries and
   creates a dist directory which houses all the programs, libraries and
   interface headers. None of the programs created by this process are
   installed onto the system using the default instructions. If you need
   any of these programs installed, you can find them in the
   mozilla/dist/bin directory of the source tree.

   export PATH=...: This command sets the PATH environment variable to
   include the executables in the source tree as some of them are required
   to run the test suite.

   sed -i 's/gmake/make/' common/init.sh: This command changes the command
   used to compile some test programs.

Contents

   Installed Programs: nspr-config and nss-config
   Installed Libraries: libcrmf.a, libfreebl3.so, libnspr4.so, libnss3.so,
   libnssckbi.so, libplc4.so, libplds4.so, libsmime3.so, libsoftokn3.so
   and libssl3.so
   Installed Directories: /usr/include/nspr and /usr/include/nss

Short Descriptions

   nspr-config

   is used to determine the NSPR installation settings of the installed
   NSPR libraries.

   nss-config

   is used to determine the NSS library settings of the installed NSS
   libraries.

   The libnspr4.so, libplc4.so and libplds4.so libraries make up the
   Netscape Portable Runtime (NSPR) libraries. These libraries provide a
   platform-neutral API for system level and libc like functions. The API
   is used in the Mozilla client, many of the Netscape/AOL/iPlanet
   offerings and other software applications.

   The libcrmf.a, libfreebl.so, libnss3.so, libnssckbi.so, libsmime3.so,
   libsoftokn3.so and libnssl3.so libraries make up the NSS libraries.

   Last updated on 2007-07-15 10:53:33 -0500

     * [9]Prev
       Sudo-1.6.9p15
     * [10]Next
       File Systems
     * [11]Up
     * [12]Home

References

   1. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/sudo.html
   2. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/filesystems.html
   3. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/security.html
   4. http://www.linuxfromscratch.org/blfs/view/6.3/index.html
   5. http://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_11_7_RTM/src/nss-3.11.7-with-nspr-4.6.7.tar.gz
   6. ftp://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_11_7_RTM/src/nss-3.11.7-with-nspr-4.6.7.tar.gz
   7. http://www.linuxfromscratch.org/patches/blfs/6.3/nss-3.11.7-with-nspr-4.6.7-fedora_fixes-1.patch
   8. http://wiki.linuxfromscratch.org/blfs/wiki/nss
   9. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/sudo.html
  10. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/filesystems.html
  11. http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/security.html
  12. http://www.linuxfromscratch.org/blfs/view/6.3/index.html
