#!/bin/sh
# Begin /etc/init.d/dbus

### BEGIN INIT INFO
# Provides:            dbus
# Required-Start:      $network
# Should-Start:        $remote_fs
# Required-Stop:       $network
# Should-Stop:         $remote_fs
# Default-Start:       3 4 5 
# Default-Stop:        0 1 2 6
# Short-Description:   Starts/Stops the D-Bus Messagebus daemon.
# Description:         Starts and stops the D-Bus Messagebus daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/bin/dbus-daemon"
MESSAGE="the D-Bus Messagebus Daemon"
CONFIGFILE="/etc/dbus-1/system.conf"
PIDFILE="/var/run/dbus/pid"
SOCKET="/var/run/dbus/system_bus_socket"
chk_stat

case "$1" in

    start)
        /usr/bin/dbus-uuidgen --ensure > /dev/null &&
        start_daemon "${BIN_FILE}" --config-file="${CONFIGFILE}"
        evaluate_retval start
    ;;

    stop)
        killproc -p "${PIDFILE}" "${BIN_FILE}"
        evaluate_retval stop
        if [ -e "${SOCKET}" ]; then
            rm "${SOCKET}" 2> /dev/null
        fi
    ;;

    force-reload)
        # -HUP not supported so just restart it.
        killproc -p "${PIDFILE}" "${BIN_FILE}"
        sleep 1
        if [ -e "${SOCKET}" ]; then
            rm "${SOCKET}" 2> /dev/null
        fi
        start_daemon "${BIN_FILE}" --config-file="${CONFIGFILE}"
        evaluate_retval force-reload
    ;;

    restart)
        killproc -p "${PIDFILE}" "${BIN_FILE}"
        sleep 1
        if [ -e "${SOCKET}" ]; then
            rm "${SOCKET}" 2> /dev/null
        fi
        start_daemon "${BIN_FILE}" --config-file="${CONFIGFILE}"
        evaluate_retval restart
    ;;

    status)
        statusproc
    ;;

    *)
        echo "Usage: $0 {start|stop|force-reload|restart|status}"
        exit 1
    ;;

esac

# End $RC_BASE/init.d/messagebus
