#!/bin/sh
# Begin /etc/init.d/gdm

### BEGIN INIT INFO
# Provides:            gpm
# Required-Start:      $network dbus
# Should-Start:        $remote_fs
# Required-Stop:       $network dbus
# Should-Stop:         $remote_fs
# Default-Start:       5
# Default-Stop:        0 1 2 3 4 6
# Short-Description:   Starts/Stops the Gnome Display Manager (GUI Login). 
# Description:         Starts and stops the Gnome Display Manager.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/opt/gnome-2.18.3/sbin/gdm"

chk_stat

case "$1" in
    start)
        MESSAGE="Starting GDM..."
        /opt/gnome-2.20/sbin/gdm
        evaluate_retval generic
        ;;

    stop)
        MESSAGE="Stopping GDM..."
        /opt/gnome-2.20/sbin/gdm-stop
        evaluate_retval generic
        ;;

    reload)
        MESSAGE="Reloding GDM (Safe)..."
        /opt/gnome-2.20/sbin/gdm-safe-restart
        evaluate_retval generic
        ;;

    restart)
        MESSAGE="Restarting GDM..."
        /opt/gnome-2.20/sbin/gdm-restart
        evaluate_retval generic
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

# End /etc/init.d/gdm
