#!/bin/sh
# Begin /etc/init.d/named

### BEGIN INIT INFO
# Provides:            named
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:         netfs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts ISC Bind name server.
# Description:         Starts ISC Bind name server.
# X-LFS-Default-Start: S22
# X-LFS-Default-Stop:  K49
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="ISC Bind nameserver"
BIN_FILE="/usr/sbin/named"
PIDFILE="/srv/named/var/run/named.pid"

case "$1" in
    start)
        start_daemon "${BIN_FILE}" -u named -t /srv/named \
                                   -c /etc/named.conf
        evaluate_retval start
    ;;

    stop)
        # slapd needs SIGINT
        killproc -p "${PIDFILE}" "${BIN_FILE}"
	evaluate_retval stop
    ;;

    restart)
        killproc -p "${PIDFILE}" "${BIN_FILE}"
        sleep 1
        start_daemon "${BIN_FILE}" -u named -t /srv/named \
                                   -c /etc/named.conf
	evaluate_retval restart
    ;;

    reload)
        /usr/sbin/rndc -c /etc/rndc.conf reload
        evaluate_retval reload
    ;;

    status)
        statusproc
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
    ;;

esac

# End $rc_base/init.d/named
